# configs/trainer/default.yaml
learning_rate: 1e-4
beta: 0.9
max_epochs: 1
accelerator: "cuda"
devices: 1
precision: 32
gradient_clip_val: 1.0
log_every_n_steps: 50
early_stopping_patience: 100 # Number of epochs with no improvement after which training will be stopped